---
title: "Top 5 States Ranked by Cases and Deaths(2020-08-22)"
author: "David J Jackson"
date: "8/23/2020"
output: 
  html_document: 
    fig_width: 9
    fig_height: 7
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RSQLite)
```
```{r}
rm(list=ls())
db <- dbConnect(RSQLite::SQLite(),dbname= "../COVIDDB/COVID.sqlite3")
```

```{r}

DF <- dbGetQuery(db,"select date,state,new_cases,new_deaths from  STATESDAILY")
DF$date <- as.Date(DF$date)
str(DF$date)
```
```{r}
df <- subset(DF,date =="2020-08-22")
df$new_cases <- sort(df$new_cases,decreasing=TRUE)
df_cases <-head(df,n=5)
barplot(new_cases ~state,data=df_cases,main="Top 5 States Ranked by single Day Cases",xlab="(For August 22, 2020)",ylab="Cases")
grid(col="black")

```
```{r}
df1 <- subset(DF,date =="2020-08-22")
df1$new_deaths <- sort(df1$new_deaths,decreasing=TRUE)
df_deaths <-head(df1,n=5)
barplot(new_deaths ~state,data=df_deaths,main="Top 5 States Rankded by Daily Deaths",xlab="(For August 22,2020)",ylab="Cases")
grid(col="black")
```

